### ISSUE TITLE
Several new features proposal

### ISSUE THREAD

**Issue by jmsche** [Orbitale/Gulpfile#2]
Hi,

I'm wondering if you could implement the following features?

### Allow building several style types together (CSS, Less, Sass)

So we can do something like:

```json
    "styles": {
        "css/main.css": [
            "file1.css",
            "file2.less",
            "file3.scss"
        ]
    },
```

### Allow directory globs

That could be useful, eg. maintaining directory structure and less configuration. So instead of having this:

```json
    "images": {
        "images/": [
            "app/Resources/public/images/*"
        ],
        "images/icons/": [
            "app/Resources/public/images/icons/*"
        ],
        "images/sidebar/": [
            "app/Resources/public/images/sidebar/*"
        ]
    },
```

We could do this:

```json
    "images": {
        "images/": [
            "app/Resources/public/images/*"
        ]
    },
```

### Prod files built in other files

Instead of calling the same command with `--prod`, just call the base command which will build the prod files at the same time, with the same filename but with ".min" in it?

So calling "gulp js" would build "app.js" and "app.min.js" at the same time.

### Sourcemaps for styles and js

Adding sourcemaps to generated js/css files (dev only) can be very useful ;) 

### Configure some way to reload the browser?

Eg. implementing a configuration to enable livereload or browser-sync?

Thanks,

jmsche

**Comment by Pierstoval** [comment]
> Allow building several style types together (CSS, Less, Sass)

It's not possible, it's a Gulp constraint. It means we should handle files one by one before merging them. Mostly, one pipe = one merging process.
That's why you can combine multiple files at once in `gulp.src()` but it's better to have only one processor for them. If you start adding less + sass to the same pipe, you can encounter unexpected issues. That's why each task is separated (as in gulp common practices).

> Allow directory globs

This is already possible, I'm using it for personal projects 😄 

> Prod files built in other files
> 
> Instead of calling the same command with --prod, just call the base command which will build the prod files at the same time, with the same filename but with ".min" in it?
> 
> So calling "gulp js" would build "app.js" and "app.min.js" at the same time.

And how would you handle it from your app? You would link the "app.js" asset and not the minified one?  For this, you would have to maintain a specific tool in your app when linking assets to handle the ".min" part in prod and in dev. I find it much more convenient to just have the full file in dev and the minified one in prod.

> Sourcemaps for styles and js

`gulp-sourcemaps` is a dependency of this gulpfile and it's actually prepared in the code but it's not activated because it depends on the developer. I personally dislike sourcemaps, I just find them useless (more code just to debug stuff, but to debug stuff it's better to put the code in dev/staging and not minify it, and it's faster than dumping a sourcemap and costs less performances :p ) but I can provide some code to activate them from the configuration.

> Configure some way to reload the browser?
> 
> Eg. implementing a configuration to enable livereload or browser-sync?

This is app-specific, as it requires a js file on frontend and this gulpfile is not meant to communicate to your frontend, only to provide you handy methods to compile your frontend with simple configuration.


Sorry not to be positive for all these answers :)

**Comment by jmsche** [comment]
> And how would you handle it from your app? You would link the "app.js" asset and not the minified one? For this, you would have to maintain a specific tool in your app when linking assets to handle the ".min" part in prod and in dev. I find it much more convenient to just have the full file in dev and the minified one in prod.

I load the correct file given a specific parameter, so that's not an issue. My idea is to generate both prod and dev assets before I push it to git, while yours requires either to generate prod assets before pushing (manually or with git hooks?) or on deploy.

> It's not possible, it's a Gulp constraint. It means we should handle files one by one before merging them. Mostly, one pipe = one merging process.

Is there no way like `.pipe(gulpif(match('*.less'), less()))`?

> gulp-sourcemaps is a dependency of this gulpfile and it's actually prepared in the code but it's not activated because it depends on the developer. I personally dislike sourcemaps, I just find them useless (more code just to debug stuff, but to debug stuff it's better to put the code in dev/staging and not minify it, and it's faster than dumping a sourcemap and costs less performances :p ) but I can provide some code to activate them from the configuration.

It allows you to know where exactly is your code when debugging it, if you merge several assets, so always useful ;)

> This is app-specific, as it requires a js file on frontend and this gulpfile is not meant to communicate to your frontend, only to provide you handy methods to compile your frontend with simple configuration.

It can also reload using a browser addon, that's why it can be interesting.

**Comment by Pierstoval** [comment]
> I load the correct file given a specific parameter, so that's not an issue. My idea is to generate both prod and dev assets before I push it to git, while yours requires either to generate prod assets before pushing (manually or with git hooks?) or on deploy.

Generated assets should not be in git, actually. Your sources are present, but the compiled ones shouldn't be versioned, else you'll encounter countless conflicts when dealing with other branches that may have other compiled contents. And merging + recompile + commit is not a solution because it adds more commits for "nothing", as you could simply not add minified files to git.

> Is there no way like `.pipe(gulpif(match('*.less'), less()))`?

As said, it's a Gulp constraint. One pipe = one stream that passes through all functions of the pipe. Imagine a pipeline transporting oil. This pipeline can pass through different factories, refineries, but you wouldn't put water in this pipeline and expect it to be drinkable at the end of the pipe. This is the same for Gulp.


> It allows you to know where exactly is your code when debugging it, if you merge several assets, so always useful ;)

I know what sourcemaps are used for. In dev you just don't need sourcemaps because your code isn't minified. If you still want to minify & sourcemap your code in dev, feel free to setup the `isProd` to `true` whatever the situation, and activate sourcemaps in the JS pipe. I may add commented stuff there later, but I think it's much better, when debugging JS, to not use sourcemaps, so the file can be properly debugged and especially can use breakpoints & debug tools in the browser's console so you don't have to reload sourcemap on each request.
To me it's useful only if you want to minify "always", but still, I think it's an overhead for nothing, as on production, minification should never impact code logic (unless you write dirty code, but then it's your linter that should throw errors on CI 😄).

It's not like if we were using transpilers from ES6 to ES5 for example, where the logic can change a little depending on the JS code you wrote. But even then, transpiling and minifying is really different, and I don't think minification is useful in dev. Our machines are performant enough to handle this, it's not like we're asking the dev server to handle thousands of requests per second therefore needing smaller files...

> It can also reload using a browser addon, that's why it can be interesting.

With a brower addon, instead of app-specific, it becomes platform-specific, meaning you may develop with one browser, and your colleague with another.

Still, using livereload plugins is easy: add it with yarn/npm, add the necessary JS to your dev environment, and just add the livereload action when watch is triggered, it's a matter of a few minutes, and as said, it's app-specific. I personally hate the idea that my browser may reload at a time where I don't want it to reload _yet_. That's why I didn't add livereload to this package.

But still, I can provide docs for this, if you like :)
